### ISSUE TITLE
Splash page isn't splashing

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm-android#166]
This disappeared after I added lazy loading. Re-add it.

**Comment by RyanTG** [comment]
Are you referring to this one? https://github.com/scottwainstock/pbm-android/blob/master/app/src/main/res/mipmap-xxxhdpi/ic_init_grey.png

Is it necessary to have two loading logos? (since we also have this one https://github.com/scottwainstock/pbm-android/blob/master/app/src/main/res/mipmap-xxxhdpi/ic_splash.png)

It doesn't feel like anything is missing to me, given how fast it initially loads now. If anything, we could replace the ic_splash.png with ic_init_grey.png, since it's a cooler graphic.

**Comment by RyanTG** [comment]
I dunno. You're right that using a drawable bitmap limits things - the image can't fill the width or height without distorting. The only way I found to resize it is to literally resize the image in an image editor. But I felt like I was just guessing the size at that point (because right now the images are the correct sizes for each resolution, but they still look small in this splash screen).

So, one solution here is to use an imageview. However, I couldn't figure out where/when to reference to that - I figured it would be in the SplashScreen.java, but that file is super confusing to me. The view that it references is region_tab_container? 

Another solution is to just have that splash logo be a little small, but make the background the proper grey so it blends in well.

It's also true that there's a moment where the old splash screen isn't loading: it's when you choose a region. You get a brief white screen.

**Comment by RyanTG** [comment]
I can keep working on this, but I haven't made good progress. Pulling back a bit, I'm actually confused as to why the original splash isn't splashing. And when I tried to change the first splash (the one that currently works) into an imageview like the other one, it stops working, as well. There are some things I can test. 

But if you happen to have a clear idea of where to go with this, feel free to do it.

**Comment by RyanTG** [comment]
I made some progress. It loads so freaking fast, though! It just flashes for a second. I'll play around with it a bit more.

The trick was to display it as a background image in the linearlayout of region_tab_container.xml, AND to use a translucent style (otherwise the screen is just white, and the image is underneath it).

**Comment by RyanTG** [comment]
Shud do it: https://github.com/scottwainstock/pbm-android/pull/176

Changing to pending.
