### ISSUE TITLE
Speed up the loading of Recently Added and Recent High Scores

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#187]
Perhaps don't pre-load the location details for all 20 entries (which I think makes sense, given that a user is likely not going to click on all 20), but instead just load the location ID. Then load the location details when an entry is clicked - which, of course, would shift the loading time to that moment, but I think that's fine.

**Comment by scottwainstock** [comment]
Here's recent machines: https://github.com/scottwainstock/pbm-android/commit/cd3f609b36ad5a07bbba00fd4f0d63cc33eca958

The score one is going to require some api work too.

**Comment by RyanTG** [comment]
Wait! Hold off on scores completely.

That doesn't include a link to location details, and thus loads quicker. I think it's ok as is.

**Comment by scottwainstock** [comment]
It loads the same extra stuff that recent machines loads though.

Here's the raw data we have available on scores:
https://pinballmapstaging.herokuapp.com/api/v1/region/portland/machine_score_xrefs.json?limit=20

... so it has to load all the LMXes in order to get the location/machine info. You can see the API hits in logcat.

So I'm surprised one would be quicker than the other.

**Comment by RyanTG** [comment]
Yeah, it's like 5 seconds. hmm

**Comment by RyanTG** [comment]
Let's close for now.
